version: "3.8"

services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs:/var/log/php
    environment:
      - TZ=${TZ:-Asia/Tokyo}

  web:
    depends_on:
      - app
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    working_dir: /work
    environment:
      - TZ=${TZ:-Asia/Tokyo}

  db:
    platform: linux/x86_64
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/var/log/mysql

volumes:
  db-store:
